update workflow

diff --git a/.github/workflows/terraform-cicd.yml b/.github/workflows/terraform-cicd.yml
--- a/.github/workflows/terraform-cicd.yml
+++ b/.github/workflows/terraform-cicd.yml
@@ -111,3 +111,30 @@ jobs:
       - name: Terraform Apply
         if: ${{ inputs.apply }}
         run: terraform apply -auto-approve plan.tfplan
+
+
+  unlock-state:
+    runs-on: ubuntu-latest
+    if: always()  # <-- This ensures it runs even if terraform job fails
+    needs: terraform
+    steps:
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@v1
+        with:
+          role-to-assume: ${{ inputs.IAM_OIDC_ROLE }}
+          aws-region: ${{ inputs.REGION }}
+
+      - name: Remove DynamoDB Lock
+        env:
+          AWS_REGION: ${{ secrets.AWS_REGION }}
+        run: |
+          # Replace with your actual LockID and table name
+          LOCK_ID="terraform-state-140023376669/state/${{ github.repository }}-terraform.tfstate"
+          TABLE_NAME="tterraform-state-140023376669"
+
+          echo "Checking for lock ID: $LOCK_ID in $TABLE_NAME"
+          aws dynamodb delete-item \
+            --table-name "$TABLE_NAME" \
+            --key "{\"LockID\": {\"S\": \"$LOCK_ID\"}}" \
+            --region "$AWS_REGION" \
+            || echo "No lock found or already removed"
