test

diff --git a/.github/workflows/terraform-destroy.yml b/.github/workflows/terraform-destroy.yml
--- a/.github/workflows/terraform-destroy.yml
+++ b/.github/workflows/terraform-destroy.yml
@@ -31,8 +31,8 @@ jobs:
       contents: read
     concurrency:
       #group: deploy-${{ github.job }}-${{ inputs.environment }}
-      group: ${{ github.workflow }}-${{ github.ref }}-${{ inputs.environment }}
-      cancel-in-progress: true
+      group: ${{ github.workflow }}-${{ inputs.environment }}
+      cancel-in-progress: false
     steps:
       - name: Print selected environment
         run: |
@@ -106,7 +106,7 @@ jobs:
     environment: ${{ inputs.environment }}
     concurrency:
       #group: deploy-${{ github.job }}-${{ inputs.environment }}
-      group: ${{ github.workflow }}-${{ github.ref }}-${{ inputs.environment }}
+      group: ${{ github.workflow }}-${{ inputs.environment }}
       cancel-in-progress: false
     steps:
       - name: Print selected environment
@@ -148,27 +148,27 @@ jobs:
         run: terraform apply -auto-approve tfdestroy.plan
         
 
-  unlock-state:
-    runs-on: ubuntu-latest
-    if: always()  # <-- This ensures it runs even if terraform job fails
-    needs: [destroy-plan,destroy-apply]
-    permissions:
-      id-token: write
-      contents: read
-    steps:
-      - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v1
-        with:
-          role-to-assume: arn:aws:iam::140023376669:role/cmrs-DEV-TH-custom-GithubOIDCRole
-          aws-region: ap-southeast-7
+  # unlock-state:
+  #   runs-on: ubuntu-latest
+  #   if: always()  # <-- This ensures it runs even if terraform job fails
+  #   needs: [destroy-plan,destroy-apply]
+  #   permissions:
+  #     id-token: write
+  #     contents: read
+  #   steps:
+  #     - name: Configure AWS credentials
+  #       uses: aws-actions/configure-aws-credentials@v1
+  #       with:
+  #         role-to-assume: arn:aws:iam::140023376669:role/cmrs-DEV-TH-custom-GithubOIDCRole
+  #         aws-region: ap-southeast-7
 
-      - name: Remove Terraform Lock
-        env:
-          AWS_REGION: ap-southeast-7
-        run: |
-          LOCK_ID="terraform-state-140023376669/state/${{ github.repository }}-terraform.tfstate.tflock"
+  #     - name: Remove Terraform Lock
+  #       env:
+  #         AWS_REGION: ap-southeast-7
+  #       run: |
+  #         LOCK_ID="terraform-state-140023376669/state/${{ github.repository }}-terraform.tfstate.tflock"
 
-          echo "Checking for lock ID: $LOCK_ID in $TABLE_NAME"
-          aws s3 rm s3://$LOCK_ID \
-            --region "$AWS_REGION" \
-            || echo "No lock found or already removed"
+  #         echo "Checking for lock ID: $LOCK_ID in $TABLE_NAME"
+  #         aws s3 rm s3://$LOCK_ID \
+  #           --region "$AWS_REGION" \
+  #           || echo "No lock found or already removed"
diff --git a/.github/workflows/terraform-plan.yml b/.github/workflows/terraform-plan.yml
--- a/.github/workflows/terraform-plan.yml
+++ b/.github/workflows/terraform-plan.yml
@@ -40,8 +40,8 @@ jobs:
       contents: read
     concurrency:
       #group: deploy-${{ github.job }}-${{ inputs.environment }}
-      group: ${{ github.workflow }}-${{ github.ref }}-${{ inputs.environment }}
-      cancel-in-progress: true
+      group: ${{ github.workflow }}-${{ inputs.environment }}
+      cancel-in-progress: false
     steps:
       - uses: actions/checkout@v3
       - uses: hashicorp/setup-terraform@v3
@@ -147,33 +147,33 @@ jobs:
             path: plan.tfplan
 
 
-  unlock-state:
-    runs-on: ubuntu-latest
-    if: always()  # <-- This ensures it runs even if terraform job fails
-    needs: terraform-plan
-    permissions:
-      id-token: write
-      contents: read
-    steps:
-      - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v1
-        if: ${{ inputs.apply }} != true
-        with:
-          role-to-assume: ${{ inputs.IAM_OIDC_ROLE }}
-          aws-region: ${{ inputs.REGION }}
+  # unlock-state:
+  #   runs-on: ubuntu-latest
+  #   if: always()  # <-- This ensures it runs even if terraform job fails
+  #   needs: terraform-plan
+  #   permissions:
+  #     id-token: write
+  #     contents: read
+  #   steps:
+  #     - name: Configure AWS credentials
+  #       uses: aws-actions/configure-aws-credentials@v1
+  #       if: ${{ inputs.apply }} != true
+  #       with:
+  #         role-to-assume: ${{ inputs.IAM_OIDC_ROLE }}
+  #         aws-region: ${{ inputs.REGION }}
 
-      - name: Remove DynamoDB Lock
-        if: ${{ inputs.apply }} != true
-        env:
-          AWS_REGION: ${{ inputs.REGION }}
-        run: |
-          # Replace with your actual LockID and table name
-          LOCK_ID="terraform-state-140023376669/state/${{ github.repository }}-terraform.tfstate"
-          TABLE_NAME="tterraform-state-140023376669"
+  #     - name: Remove DynamoDB Lock
+  #       if: ${{ inputs.apply }} != true
+  #       env:
+  #         AWS_REGION: ${{ inputs.REGION }}
+  #       run: |
+  #         # Replace with your actual LockID and table name
+  #         LOCK_ID="terraform-state-140023376669/state/${{ github.repository }}-terraform.tfstate"
+  #         TABLE_NAME="tterraform-state-140023376669"
 
-          echo "Checking for lock ID: $LOCK_ID in $TABLE_NAME"
-          aws dynamodb delete-item \
-            --table-name "$TABLE_NAME" \
-            --key "{\"LockID\": {\"S\": \"$LOCK_ID\"}}" \
-            --region "$AWS_REGION" \
-            || echo "No lock found or already removed"
+  #         echo "Checking for lock ID: $LOCK_ID in $TABLE_NAME"
+  #         aws dynamodb delete-item \
+  #           --table-name "$TABLE_NAME" \
+  #           --key "{\"LockID\": {\"S\": \"$LOCK_ID\"}}" \
+  #           --region "$AWS_REGION" \
+  #           || echo "No lock found or already removed"
