test workflow

diff --git a/.github/workflows/terraform_destroy.yml b/.github/workflows/terraform_destroy.yml
--- a/.github/workflows/terraform_destroy.yml
+++ b/.github/workflows/terraform_destroy.yml
@@ -36,10 +36,55 @@ jobs:
       - name: Terraform Init
         run: terraform init -backend-config=backend.${{ github.event.inputs.environment }}.hcl -backend-config="key=state/${{ github.repository }}-terraform.tfstate"
 
+      - id: install-aws-cli
+        uses: unfor19/install-aws-cli-action@v1
+
+      - name: Load secrets from AWS Secrets Manager
+        id: secrets
+        run: |
+          SECRET_JSON=$(aws secretsmanager get-secret-value \
+            --secret-id arn:aws:secretsmanager:ap-southeast-7:140023376669:secret:test-4YV1Ej \
+            --query SecretString \
+            --output text)
+
+          # Parse each key into TF_VAR_ environment variables
+          echo "$SECRET_JSON" | jq -r 'to_entries[] | "\(.key)=\(.value)"' | while IFS='=' read -r key value; do
+            echo "::add-mask::$value"                     
+            echo "TF_VAR_$key=$value" >> "$GITHUB_ENV"    
+          done
 
       - name: Terraform Plan
         run: terraform plan -var-file=terraform.${{ github.event.inputs.environment }}.tfvars -out=plan.tfplan
 
-      - name: Terraform Plan
+      - name: Terraform Destroy
         run: terraform apply -auto-approve plan.tfplan
         
+
+  unlock-state:
+    runs-on: ubuntu-latest
+    if: always()  # <-- This ensures it runs even if terraform job fails
+    needs: terraform
+    permissions:
+      id-token: write
+      contents: read
+    steps:
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@v1
+        with:
+          role-to-assume: arn:aws:iam::140023376669:role/cmrs-DEV-TH-custom-GithubOIDCRole
+          aws-region: ap-southeast-7
+
+      - name: Remove DynamoDB Lock
+        env:
+          AWS_REGION: ap-southeast-7
+        run: |
+          # Replace with your actual LockID and table name
+          LOCK_ID="terraform-state-140023376669/state/${{ github.repository }}-terraform.tfstate"
+          TABLE_NAME="tterraform-state-140023376669"
+
+          echo "Checking for lock ID: $LOCK_ID in $TABLE_NAME"
+          aws dynamodb delete-item \
+            --table-name "$TABLE_NAME" \
+            --key "{\"LockID\": {\"S\": \"$LOCK_ID\"}}" \
+            --region "$AWS_REGION" \
+            || echo "No lock found or already removed"
